### ISSUE TITLE
Filter by country is stupid. Renewables have to be seen on a more collaborative way. Allow to combine countries please, and f.i. the selection Europe.

### ISSUE THREAD

**Issue by DidierVdM** [PyPSA/whobs-server#17]
Not one energie-system is self-sustainable. All have today connections between countries. Therefor  you cannot restrict this on country nor region level. You have to be able to see a wider picture. Please let me know when this is useable.

**Comment by nworbmot** [comment]
This is already mentioned in the list of warnings about the model. You can also select larger regions by polygon. I've blocked you for unconstructive rudeness.
