### ISSUE TITLE
Real World demand data input

### ISSUE THREAD

**Issue by freechelmi** [PyPSA/whobs-server#19]
Hi , First congrats for this great amazing tool

Currently it seems to be only possible to specify a constant demand for electricity which leads to huge capacity du to the fact that we cannot balance with low demand overnight.

it would great to be able to load csv file at first for demand. We already have csv file from French RTE https://www.rte-france.com/eco2mix

Do you feel it would be a really difficult task ?

**Comment by nworbmot** [comment]
It just needs to be programmed! See https://github.com/PyPSA/whobs-server/issues/8.

**Comment by freechelmi** [comment]
Duplicate of #8
