### ISSUE TITLE
build_cutout.py not working - request failed

### ISSUE THREAD

**Issue by pz-max** [PyPSA/whobs-server#20]
I followed the README.md and run the `python build_cutout.py`
The default lat/lon definitions lead to a failed request
`Exception: no data is available within your requested subset. Request returned no data`

Full API request:
reanalysis-era5-single-levels
Request body:
```
{
  "area": [
    90,
    -180,
    -90,
    -90
  ],
  "day": 1,
  "format": "netcdf",
  "month": 12,
  "product_type": "reanalysis",
  "time": [
    "00:00",
    "01:00",
    "02:00",
    "03:00",
    "04:00",
    "05:00",
    "06:00",
    "07:00",
    "08:00",
    "09:00",
    "10:00",
    "11:00",
    "12:00",
    "13:00",
    "14:00",
    "15:00",
    "16:00",
    "17:00",
    "18:00",
    "19:00",
    "20:00",
    "21:00",
    "22:00",
    "23:00"
  ],
  "variable": "orography",
  "year": 2014
}
```

**Comment by nworbmot** [comment]
Fix as of https://github.com/PyPSA/whobs-server/commit/a1aae46b28437fb1d624a6662426fa20316e6a58.
